import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Choose your lessons</h1>
        <div className={styles.price_container}>
          <div className={styles.price_card_item}>
            <h1>10</h1>
            <h3>Weeks</h3>
            <div className={styles.img_svg_container}></div>
            <div className={styles.btn_container}>
              <button>Buy Now</button>
            </div>
          </div>
          <div className={styles.price_card_item}>
            <h1>20</h1>
            <h3>Weeks</h3>
            <div className={styles.img_svg_container}></div>
            <div className={styles.btn_container}>
              <button>Buy Now</button>
            </div>
          </div>
          <div className={styles.price_card_item}>
            <h1>30</h1>
            <h3>Weeks</h3>
            <div className={styles.img_svg_container}></div>
            <div className={styles.btn_container}>
              <button>Buy Now</button>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
